// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: speaking.proto

package speaking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpeakingAssessmentService_AssessSpeaking_FullMethodName = "/speaking.SpeakingAssessmentService/AssessSpeaking"
)

// SpeakingAssessmentServiceClient is the client API for SpeakingAssessmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpeakingAssessmentServiceClient interface {
	AssessSpeaking(ctx context.Context, in *SpeakingAssessmentRequest, opts ...grpc.CallOption) (*SpeakingAssessment, error)
}

type speakingAssessmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeakingAssessmentServiceClient(cc grpc.ClientConnInterface) SpeakingAssessmentServiceClient {
	return &speakingAssessmentServiceClient{cc}
}

func (c *speakingAssessmentServiceClient) AssessSpeaking(ctx context.Context, in *SpeakingAssessmentRequest, opts ...grpc.CallOption) (*SpeakingAssessment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpeakingAssessment)
	err := c.cc.Invoke(ctx, SpeakingAssessmentService_AssessSpeaking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpeakingAssessmentServiceServer is the server API for SpeakingAssessmentService service.
// All implementations must embed UnimplementedSpeakingAssessmentServiceServer
// for forward compatibility.
type SpeakingAssessmentServiceServer interface {
	AssessSpeaking(context.Context, *SpeakingAssessmentRequest) (*SpeakingAssessment, error)
	mustEmbedUnimplementedSpeakingAssessmentServiceServer()
}

// UnimplementedSpeakingAssessmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpeakingAssessmentServiceServer struct{}

func (UnimplementedSpeakingAssessmentServiceServer) AssessSpeaking(context.Context, *SpeakingAssessmentRequest) (*SpeakingAssessment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssessSpeaking not implemented")
}
func (UnimplementedSpeakingAssessmentServiceServer) mustEmbedUnimplementedSpeakingAssessmentServiceServer() {
}
func (UnimplementedSpeakingAssessmentServiceServer) testEmbeddedByValue() {}

// UnsafeSpeakingAssessmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeakingAssessmentServiceServer will
// result in compilation errors.
type UnsafeSpeakingAssessmentServiceServer interface {
	mustEmbedUnimplementedSpeakingAssessmentServiceServer()
}

func RegisterSpeakingAssessmentServiceServer(s grpc.ServiceRegistrar, srv SpeakingAssessmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedSpeakingAssessmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpeakingAssessmentService_ServiceDesc, srv)
}

func _SpeakingAssessmentService_AssessSpeaking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpeakingAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeakingAssessmentServiceServer).AssessSpeaking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeakingAssessmentService_AssessSpeaking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeakingAssessmentServiceServer).AssessSpeaking(ctx, req.(*SpeakingAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpeakingAssessmentService_ServiceDesc is the grpc.ServiceDesc for SpeakingAssessmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpeakingAssessmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speaking.SpeakingAssessmentService",
	HandlerType: (*SpeakingAssessmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssessSpeaking",
			Handler:    _SpeakingAssessmentService_AssessSpeaking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "speaking.proto",
}
